### ISSUE TITLE
Strange behaviour after updating BOTW using mapleseed

### ISSUE THREAD

**Issue by Snadder** [Tsume/Maple-Tree#131]
The issue is that when I open CEMU after having updated it will use a staggering amount of ram ( upwards of 16 GB with page file) even before CEMU compiles the shaders and then predictably so crashes. I am using the latest version of mapleseed 2 and I use CEMU version 1.10.0f.

**Comment by knwt** [comment]
Same here. Without updating via maple seed I can boot the game. After updating is a instant crash

**Comment by Snadder** [comment]
Well I just went back to mapleseed 1 and now it works just fine, though Tsume should look into this anyway.

**Comment by Squall-Leonhart** [comment]
something seems to be broken with the download function, it fails the first time, says things are finished downloading while they show 0KB files.

start again and DLQ (queue) occurs, loads TMD and then goes through the download, decrypts and puts things where they should be, however it seems to be missing things because as knwt has said, the game crashes immediately

**Comment by Squall-Leonhart** [comment]
2.1.1.16 seems ok

**Comment by Tsume** [comment]
2.1.1.17 has broken downloads. Use 2.1.1.16 for now. A fixed version of 2.1.1.17 will be uploaded soon(tm)

**Comment by Tsume** [comment]
I actually can't recall if I uploaded it yet or not. Redownload 2.1.1.17 and try it, if it does the same thing let me know.

**Comment by Squall-Leonhart** [comment]
You haven't.

![image](https://user-images.githubusercontent.com/1098176/32033577-f4df316c-ba58-11e7-80dd-bd76c8d824c9.png)

**Comment by Tsume** [comment]
I've published a new build that should fix the download issue.
2.1.1.17b
