### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by nergaard2k** [Tsume/Maple-Tree#22]
well i installed it and launched it selected cemu folder and it crashed

**Comment by Tsume** [comment]
What language?
What folder?
Which version?
Which build?
What error if any?

**Comment by nergaard2k** [comment]
version 2 and cemu 1.7.3b  standard fresh

**Comment by r0bodog** [comment]
Mapleseed v2.1.1.8 standard installer from latest release page.

Crashes on startup. Event viewer shows these 3 errors:

**Source: .NET Runtime**
Application: MapleSeedU2.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileSystemEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CommonInit()
   at System.IO.Directory.GetFiles(System.String, System.String)
   at MapleLib.Collections.MapleDictionary+<LoadTitle>d__27.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Source: Application Error**
Faulting application name: MapleSeedU2.exe, version: 2.1.0.200, time stamp: 0x58d8716c
Faulting module name: KERNELBASE.dll, version: 10.0.14393.726, time stamp: 0x58785749
Exception code: 0xe0434352
Fault offset: 0x0000000000017788
Faulting process id: 0x1894
Faulting application start time: 0x01d2aa339a53c885
Faulting application path: C:\Users\USERNAME\Downloads\MapleSeedU2.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: abd7902c-fa58-40ca-a7bd-6d7def688894
Faulting package full name: 
Faulting package-relative application ID: 

**Source: Windows Error Reporting**
Fault bucket , type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: MapleSeedU2.exe
P2: 2.1.0.200
P3: 58d8716c
P4: mscorlib
P5: 4.6.1637.0
P6: 586fe5fa
P7: 1587
P8: fd
P9: System.IO.DirectoryNotFound
P10: 

Attached files:

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_MapleSeedU2.exe_912f3cbda91d7193c1eaf87f1c0968afb8c1c2_e7da7e03_31bb7a5e 
[Report.zip](https://github.com/Tsume/Maple-Tree/files/886167/Report.zip)


Analysis symbol: 
Rechecking for solution: 0
Report Id: abd7902c-fa58-40ca-a7bd-6d7def688894
Report Status: 101
Hashed bucket:

**Comment by Tsume** [comment]
Make sure you're running it as Administrator, it's missing a folder. All missing folders should be auto created as needed.

**Comment by Frostbite96** [comment]
I have the exact same issue, version 2 and CEMU 1.7.3c

**Comment by Tsume** [comment]
Look in your AppData folder under Users -> AppData > Roaming > MapleTree. Zip that folder and upload it to here.

**Comment by Frostbite96** [comment]
[https://www.dropbox.com/s/7a5wpd9webkf6h4/MapleTree.zip?dl=0](url)

**Comment by Tsume** [comment]
It may be due to the non-english(?) character. Try this:

Delete the directory MapleTree, and re-run MapleSeed. 
Select a directory with only letters A~B (Ex: C:\cemu\cemu.exe)

Let me know if this works, if it does, I'll look into adding support for other language characters.

**Comment by Frostbite96** [comment]
It worked. Thank you.

**Comment by Zangetsu38** [comment]
Not Works sorry, i have tryed delete folder and re launch MapleSeed2 but same think crach infinite
![image](https://cloud.githubusercontent.com/assets/5261759/26605388/18642bc8-458e-11e7-9e68-fc16c15da509.png)
