### ISSUE TITLE
empty game library & SSL connection error

### ISSUE THREAD

**Issue by tweetos** [Tsume/Maple-Tree#381]
after downloading mapleseed, CEMU 1.11.6b and BOTW I ran mapleseed and specified both game library folder and CEMU.exe location. The library stays loading for hours but i can see BOTW in cemu which i need to update.

### Version Used
2.1.1.18

**Comment by feikname** [comment]
Same problem. BOTW displays (v33) but there's no option in the context menu to update it.

Additionally, there's something in the log about a secure SSL/TLS connection not being able to be stablished. Unfortunately, I can't copy-paste the entire stacktrace here because the log is unselectable.

Maybe someone forgot to renew a cert? 😆

**Comment by Tsume** [comment]
The lack of version for botw is due to the database missing those entries(someone removed them). I plan on restoring a version that has them sometime today or tomorrow. The SSL issue was fixed in a build I'm currently working on. I'll attach it to this reply so you and others can use it while I complete other fixes/changes.

[MapleSeed2.zip](https://github.com/Tsume/Maple-Tree/files/1976817/MapleSeed2.zip)
