### ISSUE TITLE
Multiple Graphics Packs?

### ISSUE THREAD

**Issue by gogocons** [Tsume/Maple-Tree#40]
Is there currently a way to select multiple graphics packs that is not obvious (ex, BotW 1080p and AA removal)? Also, would there be a way to select no graphics pack for games that have ones I do not want.

**Comment by Tsume** [comment]
You can disable graphic packs on the control panel. Currently, it only does one(for simplicity purposes).
I plan to improve it to handle multiple packs in the future.

**Comment by gogocons** [comment]
I may be unclear on how the feature currently works but I don't think simply disabling it from the options is the functionality that is desired for most users. Currently (as I understand it) to enable graphics packs and have them launch with MapleSeed, one must: 1. enable graphics packs 2. close MapleSeed 3. relaunch MapleSeed 4. select graphic pack for game (and only one at this time) 5. launch game. In order to launch a game with no graphics pack, there could be an option to select [BLANK] or No Graphics Pack Please, instead of going into the control panel turning off and closing/relaunching MapleSeed. This is not a deal breaker just a suggestion and/or observation. Let me know your thoughts!

**Comment by Tsume** [comment]
That's what the toggle is for. It's a global option that prevents graphic packs from being added/alterd in cemu's directory. The restarts aren't required.(I make a point to not require restarts for anything, it's lame and kind of lazy)

Example: You don't want a graphic pack added when launching Mario Kart, regardless of what pack is selected. If you deselect the toggle. You'll be launching with non-graphic packed Mario Kart. Want it on? Close cemu, switch the toggle and launch cemu and it's added as usual.

At least that's how it should be. If it doesn't work that way let me know, since it's likely to be a bug/oversight.

**Comment by Tsume** [comment]
But I do see what you mean. It wouldn't be much effort to add a blank pack so you can launch without one instead of having to toggle the global switch. I'll make a note to add that into the next release.

**Comment by Tsume** [comment]
No graphic pack option added in commit https://github.com/Tsume/Maple-Tree/commit/d4958fd3b215e50351e936b7cb80aa0056d37fd7

Multi-packs coming later
